# src/OC/PlatformBundle/Resources/config/routing.yml
oc_platform_CroCombo:
    path:     /
    defaults: { _controller: OCPlatformBundle:Advert:test }



oc_platform_home:
    path:      /
    defaults: { _controller: OCPlatformBundle:Advert:index }


oc_platform_view:
    path:      /advert/{id}
    defaults: { _controller: OCPlatformBundle:Advert:view }


oc_platform_add:
    path:      /add
    defaults: { _controller: OCPlatformBundle:Advert:add }


oc_platform_view_slug:
    path:      /{year}/{slug}.{format}
    defaults: 
        _controller: OCPlatformBundle:Advert:viewSlug
        format:     html
#   defaults: { _controller: OCPlatformBundle:Advert:viewSlug, format: html }  # permet d'ajouter la possibilité pour{format}de ne pas être renseigné elle est donc par "default" et peut s'ecrire sur une ligne
    requirements:
        year:   \d{4}
        format: html|xml|buz
        _locale: fr
